networks:
  proxy:
    name: proxy

volumes:
  config:
  cache:
  media:
    driver: local
    driver_opts:
      o: bind
      type: exfat
      device: /mnt/media

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped

    volumes:
      - config:/config
      - cache:/cache
      - media:/media

    networks:
      proxy:
    ports:
      - 80:8096
