version: "3.8"

volumes:
  config:
  cache:

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped

    volumes:
      - cache:/cache
      - config:/config
      - mnt/media:/media

    ports:
      - 80:8096
