version: "3.3"

networks:
  proxy:
    name: proxy

services:
  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    networks:
      proxy:
    ports:
      - 80:80
