- name: Add SSH Keys
  become: true
  hosts: nodes
  tasks:
    - name: Install Public Keys
      ansible.posix.authorized_key:
        user: "{{ hostvars[inventory_hostname]['ansible_ssh_user'] }}"
        key: "{{ lookup('file', '~/.ssh/keys.pub') }}"
        state: present
