- name: Install Watchtower
  hosts: nodes
  become: true
  tasks:
    - name: Deploy Watchtower
      community.docker.docker_container:
        name: watchtower
        image: container/watchtower
        restart_policy: unless-stopped
        container_name: watchtower

        command: --schedule "0 0 4 * * *" --debug

        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
